// @ts-nocheck
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { createClient } from "@/lib/supabase/server";
import LoginForm from "@/components/LoginForm";
import BackgroundGradientLayer from "@/components/BackgroundGradientLayer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  // console.log("data after login", data);
  const user = data?.user?.user_metadata;
  return (
    <>
      {/* <BackgroundGradientLayer /> */}
      {/* {!user && <BackgroundGradientLayer />} */}
      <div className="relative">
        <Header user={user} />
        <main>{children}</main>
        {/* <div className="h-[170px]"></div> */}

        <Footer />
      </div>
    </>
  );
}
