// @ts-nocheck
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { createClient } from "@/lib/supabase/server";
import LoginForm from "@/components/LoginForm";
import BackgroundGradientLayer from "@/components/BackgroundGradientLayer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  // console.log("data after login", data);
  const user = data?.user?.user_metadata;
  return (
    <>
      {!user && <BackgroundGradientLayer />}
      <div className="relative">
        <Header user={user} />
        <main>{children}</main>
        <svg
          viewBox="0 0 740 100"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className="cdl3wy9"
        >
          <path
            d="M 230 74.9998 C 221.5 71.9995 190.5 22.4998 69 18.4998 C 45.6329 17.7305 25.6317 19.3469 8.56594 22.4598 C 4.15502 23.2644 0 24.9389 0 23.4552 V 108 H 740 V 60.9843 C 794 65.0822 736.496 68.3004 732.408 68.01 C 729.819 67.8261 727.184 67.6558 724.5 67.4998 C 595.5 59.9998 582 95 573.5 94.9998 C 565 94.9995 532 58.9998 406 47.4998 C 280 35.9998 238.5 78 230 74.9998 Z"
            fill="white"
            stroke="#e9e9e9"
          ></path>
        </svg>
        <Footer />
      </div>
    </>
  );
}
