// @ts-nocheck
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { createClient } from "@/lib/supabase/server";
import LoginForm from "@/components/LoginForm";
import BackgroundGradientLayer from "@/components/BackgroundGradientLayer";

// import "./mux-player.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = await createClient();
  const { data } = await supabase.auth.getUser();
  // console.log("data after login", data);
  const user = data?.user?.user_metadata;
  return (
    <html lang="en">
      <body className={`${GeistSans.className} antialiased`}>
        <BackgroundGradientLayer />
        <div className="relative">
          {/* {user && <Header />} */}
          <Header />
          <main>{children}</main>
          {/* {user && <Footer />} */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
